name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualiza checkout también

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Versión más reciente
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run custom tests
        run: npm run test:ci
        env:
          CI: true

      - name: Publish Test Results
        uses: actions/upload-artifact@v4  # Versión correcta
        with:
          name: test-results
          path: ./test-results/**/*.xml

      - name: Publish Coverage
        uses: codecov/codecov-action@v4  # Actualiza codecov si es necesario
        with:
          file: coverage/lcov.info
